### ISSUE TITLE
M-LOAM特征筛选部分问题

### ISSUE THREAD

**Issue by chengwei0427** [narutojxl/M-LOAM_noted#1]
@narutojxl  你好，

看到你在[M-LOAM](https://github.com/gogojjh/M-LOAM)里的issue，有些问题想请教一下；

q1：请问有测试过M-LOAM的实时性吗？多激光能达到实时使用吗？

q2: 最近想测试greedy feature select部分，所以参考M-LOAM，把特征筛选部分代码拿出来使用；目前是把这块代码，直接放到了fastlio2的h_share_model部分，以32线雷达采集的数据进行测试，测试发现，筛选特征蛮费时，在求解motion时（使用特征筛选比例为原始特征的30%），10次以上还没有收敛，导致激光里程计达不到实时要求；不知道是不是我哪里设置的有问题，请问关于greedy feature select这部分，你有做过这方面的测试吗？

**Comment by narutojxl** [comment]
Hello @chengwei0427,  你好，
实在不好意思，当时阅读m-loam的代码时，作者good feature的文章还没挂出来，也就没有看这部分代码的实现。greedy feature 这部分实时性没有测试，实在抱歉。要不试试在原作者的主页问问看大家有没有其他人测过。

**Comment by chengwei0427** [comment]
你好， @narutojxl ，
        
        感谢回复！
  
       我又看了一遍作者的文章及代码实现，在代码中，作者的mapping部分，最大迭代次数为2次，而在文章及补充材料中，给出的运行时间如下（其中上图为Intel NUC，补充材料给出）

![image](https://user-images.githubusercontent.com/20199999/199871976-7051e1f2-3489-4e80-9758-14ea17b5212d.png)
![image](https://user-images.githubusercontent.com/20199999/199872032-bf30c1e0-83a9-40a1-b51e-4d4ab1ba8b22.png)

所以greedy feature select这部分应该就是比较费时的。
